In [1]:
import pandas as pd
import numpy as np
import csv as csv
import os
import sys
import codecs
import time
import matplotlib.pyplot as plt
from datetime import datetime
import seaborn as sns 
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from matplotlib.font_manager import FontProperties
from collections import Counter
from sklearn.linear_model import LinearRegression
from scipy import stats
import psutil
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline
#myfont = FontProperties(fname=r'/var/anaconda3/jupyter/derrick.wu/msjh.ttc')
pd.set_option('display.max_columns',1000)

In [2]:
from datetime import datetime

In [4]:
#for i in range(12)
as041701 = pd.read_csv(r'C:\Users\derrick.wu\Documents\DW\income\CSV\AS\AS041712.csv',header=0,encoding = 'ansi',dtype={'AGNTNUM':str})

In [5]:
as041701.head()

,TRANCD,JOURNAL_NO,USSEQNO,USSEQ,COMP_NO,AGNTNUM,INCOME_NO,REAMT,WNOTE,MODDATE,POLICYNO,BILLNO,SOUFILE,SOUKEY,DISKSEQ,JOB_NAME,USER_PROFI,FEAT_AMT
0,US02,68690,685844910.0,8896760.0,P,00001278,G22,1132.0,楊世光 年繳 015NT410030,20171020,57029161,NT410030,AC08ENQ,808346351,0,L2ACSMTH08,WHDACOP01,0.0
1,US02,68690,685844911.0,8896760.0,P,00001278,G23,232.0,楊世光 年繳 015NT410030,20171020,57029161,NT410030,AC08ENQ,808346352,0,L2ACSMTH08,WHDACOP01,0.0
2,US02,68690,685844912.0,8896760.0,P,00001278,G23,95.0,楊世光 年繳 015NT410030,20171020,57029161,NT410030,AC08ENQ,808346353,0,L2ACSMTH08,WHDACOP01,0.0
3,US02,68690,685844913.0,8896760.0,P,00001278,G22,45.0,韓玉華 月繳 232RW359918,20171118,26524538,RW359918,AC08ENQ,828179190,0,L2ACSMTH08,WHDACOP01,0.0
4,US02,68690,685844914.0,8896760.0,P,00001278,G22,175.0,楊烈瑾 季繳 074RW361352,20171123,27503086,RW361352,AC08ENQ,828199430,0,L2ACSMTH08,WHDACOP01,0.0

In [3]:
ab = pd.read_csv(r'C:\Users\derrick.wu\Documents\DW\income\2017\CSV\AB011701.csv',header=0,encoding = 'ansi',dtype={'業務員代碼':str})

FileNotFoundError: File b'C:\\Users\\derrick.wu\\Documents\\DW\\income\\2017\\CSV\\AB011701.csv' does not exist

In [4]:
as041701.head()

,TRANCD,JOURNAL_NO,USSEQNO,USSEQ,COMP_NO,AGNTNUM,INCOME_NO,REAMT,WNOTE,MODDATE,POLICYNO,BILLNO,SOUFILE,SOUKEY,DISKSEQ,JOB_NAME,USER_PROFI,FEAT_AMT
0,US02,59981,608157186.0,7780267.0,P,00001278,G22,156.0,張舜嘉 月繳 041,20161124,81792692,NaN,AC08ENQ,732218296,0,L2ACSMTH08,WHDACOP01,0.0
1,US02,59981,608157187.0,7780267.0,P,00001278,G23,9.0,張舜嘉 月繳 041,20161124,81792692,NaN,AC08ENQ,732218297,0,L2ACSMTH08,WHDACOP01,0.0
2,US02,59981,608157188.0,7780267.0,P,00001278,G23,4.0,張舜嘉 月繳 041,20161124,81792692,NaN,AC08ENQ,732218298,0,L2ACSMTH08,WHDACOP01,0.0
3,US02,59981,608157189.0,7780267.0,P,00001278,G23,5.0,張舜嘉 月繳 041,20161124,81792692,NaN,AC08ENQ,732218299,0,L2ACSMTH08,WHDACOP01,0.0
4,US02,59981,608157190.0,7780267.0,P,00001278,G22,12.0,張舜嘉 月繳 041,20161124,81792692,NaN,AC08ENQ,732218300,0,L2ACSMTH08,WHDACOP01,0.0

In [5]:
ab.head()

,業務員代碼,工作月份,ALLOCATED_,處經理組,區經理組,襄理組織,DSEQNO,業代,職務代號,REPORTAG,主管職位代,處經理業,處經理職,區經理業,區經理職,襄理業務代,襄理職位代,主任業務代,主任職位代,通訊處代碼,業績責任額,DATE_APPOI,ERROR_FLAG
0,00010273,201701,683,13,1,1,1,1,AC,NaN,NaN,10273,AC,10273,AC,10273,AC,10273,AC,QQ015,6600.0,19991201,NaN
1,00012779,201701,2774,39,1,1,1,1,AE,NaN,NaN,12779,AE,12779,AE,12779,AE,12779,AE,GG005,0.0,19970201,NaN
2,00014011,201701,4700,65,1,1,1,1,AC,NaN,NaN,14011,AC,14011,AC,14011,AC,14011,AC,QQ030,6200.0,19991213,NaN
3,00014478,201701,5172,69,1,1,1,1,AF,NaN,NaN,14478,AF,14478,AF,14478,AF,14478,AF,QQ082,1800.0,20001204,NaN
4,00015101,201701,1560,26,1,1,1,1,AB,NaN,NaN,15101,AB,15101,AB,15101,AB,15101,AB,QQ056,3900.0,20000705,NaN

In [ ]:
#KPI 找到每個人的FYC+RYC+OR+Other

In [24]:
ab['業務員代碼'].nunique()
#1048575

10967

In [7]:
sector=as041701.groupby(by='AGNTNUM')

In [27]:
as041701.head()

,TRANCD,JOURNAL_NO,USSEQNO,USSEQ,COMP_NO,AGNTNUM,INCOME_NO,REAMT,WNOTE,MODDATE,POLICYNO,BILLNO,SOUFILE,SOUKEY,DISKSEQ,JOB_NAME,USER_PROFI,FEAT_AMT
1047318,US02,59981,609379503.0,7780309.0,P,00003170,1L,-52.0,誠實保險手續費,20170204,NaN,NaN,AU11SEL,17900593,0,L2ACSMTH08,WHDACOP01,0.0
1047762,US02,59981,609379947.0,7780357.0,P,00004147,1L,-52.0,誠實保險手續費,20170204,NaN,NaN,AU11SEL,17900641,0,L2ACSMTH08,WHDACOP01,0.0
1047499,US02,59981,609379684.0,7780333.0,P,00003541,1L,-52.0,誠實保險手續費,20170204,NaN,NaN,AU11SEL,17900616,0,L2ACSMTH08,WHDACOP01,0.0
1048420,US02,59981,609380605.0,7780449.0,T,00007512,1L,-52.0,誠實保險手續費,20170204,NaN,NaN,AU11SEL,17900726,0,L2ACSMTH08,WHDACOP01,0.0
1048419,US02,59981,609380604.0,7780448.0,N,00007508,1L,-52.0,誠實保險手續費,20170204,NaN,NaN,AU11SEL,17900725,0,L2ACSMTH08,WHDACOP01,0.0

In [80]:
data=sector.get_group('00003170')

In [35]:
type(data)

pandas.core.frame.DataFrame

In [159]:
sector=as041701.groupby(by='AGNTNUM')
FYC_list=['G11', 'G12', 'G13', 'G14',
          'G31', 'G34', 'G37', 'G36']
RYC_list=['G22', 'G23', 'G21', 'G24', 'G25']
OR_list=['FT','FU','YC', 'YD','FV','BK','OT','BZ','QB', 'FY',"F2","YB"]
Other_list=['FX1','PK','QB',
            'SH1', 'SH2', 'SH3', 'SH4', 'SH5','SH6', 'SH8', 'SH9', 
            'SI1', 'SI2', 'SI3', 'SI5', 'SI6', 'SI7','SI8', 'SI9']
FYC_Income_list=[]
RYC_Income_list=[]
OR_Income_List=[]
Other_Income_List=[]
total_Income_list=[]

month_table=pd.DataFrame(columns=['TRANCD','JOURNAL_NO','AGNTNUM','FYC','RYC','OR','Other'],index=['0'])
Agent_list=as041701['AGNTNUM'].unique()
for i in Agent_list:
    #temptable=pd.DataFrame()
    data=sector.get_group(i).reset_index(drop=1)
    #篩出來沒東西檢查一下
    FYC_table = data[data['INCOME_NO'].isin(FYC_list)]
    RYC_table = data[data['INCOME_NO'].isin(RYC_list)]
    OR_table = data[data['INCOME_NO'].isin(OR_list)]
    Other_table = data[data['INCOME_NO'].isin(Other_list)]
    FYC_Income=sum(FYC_table['REAMT'])
    FYC_Income_list=FYC_Income_list+[FYC_Income]
    
    RYC_Income=sum(RYC_table['REAMT'])
    RYC_Income_list=RYC_Income_list+[RYC_Income]
    
    OR_Income=sum(OR_table['REAMT'])
    OR_Income_List=OR_Income_List+[OR_Income]
    
    Other_Income=sum(Other_table['REAMT'])
    Other_Income_List=Other_Income_List+[Other_Income]
    
    total=FYC_Income+RYC_Income+OR_Income+Other_Income
    total_Income_list=total_Income_list+[total]
    
    dict_={
    'TRANCD':data.TRANCD[0],
    'JOURNAL_NO':data.JOURNAL_NO[0],
    'AGNTNUM':Agent_list,
    'FYC':FYC_Income_list,
    'RYC':RYC_Income_list,
    'OR':OR_Income_List,
    'Other':Other_Income_List, 
    'Total':total_Income_list
    }
month_table=pd.DataFrame(dict_)
#del temptable

In [151]:
temptable

  TRANCD  JOURNAL_NO   AGNTNUM  FYC  RYC      OR  Other
0   US02       59981  00004147    0    0  3087.0      0

In [162]:
monthtable_merge=month_table.merge(ab,how='left',left_on=['AGNTNUM'],right_on=['業務員代碼'])

In [165]:
monthtable_merge.sort_values(by='Total',ascending=0)

,TRANCD,JOURNAL_NO,AGNTNUM,FYC,RYC,OR,Other,Total,業務員代碼,工作月份,ALLOCATED_,處經理組,區經理組,襄理組織,DSEQNO,業代,職務代號,REPORTAG,主管職位代,處經理業,處經理職,區經理業,區經理職,襄理業務代,襄理職位代,主任業務代,主任職位代,通訊處代碼,業績責任額,DATE_APPOI,ERROR_FLAG
2032,US02,59981,10099734,1531394.0,0.0,216845.0,15000.0,1763239.0,10099734,201701.0,8405.0,115.0,6.0,3.0,2.0,1.0,D1,10088077.0,C1,7946.0,AB,10035362.0,B1,10088077.0,C1,10099734.0,D1,JJ048,0.0,20151215.0,NaN
198,US02,59981,00027479,7832.0,709556.0,885655.0,1800.0,1604843.0,00027479,201701.0,2088.0,32.0,1.0,1.0,1.0,1.0,AA,18153.0,AA,27479.0,AA,27479.0,AA,27479.0,AA,27479.0,AA,AA013,4400.0,19920201.0,NaN
193,US02,59981,00018153,3730.0,624822.0,759156.0,1800.0,1389508.0,00018153,201701.0,3141.0,44.0,1.0,1.0,1.0,1.0,AA,NaN,NaN,18153.0,AA,18153.0,AA,18153.0,AA,18153.0,AA,AA001,1800.0,19920201.0,NaN
201,US02,59981,00026933,4462.0,535113.0,814326.0,1800.0,1355701.0,00026933,201701.0,8840.0,122.0,1.0,1.0,1.0,1.0,AA,18153.0,AA,26933.0,AA,26933.0,AA,26933.0,AA,26933.0,AA,EE004,3900.0,19921001.0,NaN
202,US02,59981,10002669,725.0,348035.0,459483.0,1800.0,810043.0,10002669,201701.0,1088.0,21.0,1.0,1.0,1.0,1.0,AB,10523.0,AA,10002669.0,AB,10002669.0,AB,10002669.0,AB,10002669.0,AB,LL008,2100.0,20020722.0,NaN
1027,US02,59981,00023918,404142.0,77829.0,247331.0,0.0,729302.0,00023918,201701.0,8626.0,118.0,1.0,1.0,1.0,1.0,AF,NaN,NaN,23918.0,AF,23918.0,AF,23918.0,AF,23918.0,AF,QQ038,3200.0,20000114.0,NaN
3247,US02,59981,10007556,540511.0,53961.0,76536.0,0.0,671008.0,10007556,201701.0,3531.0,47.0,1.0,1.0,3.0,1.0,D1,23964.0,AF,23964.0,AF,23964.0,AF,23964.0,AF,10007556.0,D1,AA031,0.0,20030328.0,NaN
653,US02,59981,00042548,321570.0,105270.0,228966.0,0.0,655806.0,00042548,201701.0,771.0,15.0,1.0,1.0,1.0,1.0,AF,10273.0,AC,42548.0,AF,42548.0,AF,42548.0,AF,42548.0,AF,QQ120,0.0,20020130.0,NaN
3746,US02,59981,10038469,350916.0,155568.0,133650.0,0.0,640134.0,10038469,201701.0,276.0,6.0,3.0,1.0,1.0,1.0,B1,10001668.0,B3,28964.0,AF,10038469.0,B1,10038469.0,B1,10038469.0,B1,JJ062,0.0,20070910.0,NaN
2374,US02,59981,10088077,67305.0,2068.0,542448.0,0.0,611821.0,10088077,201701.0,8400.0,115.0,6.0,3.0,1.0,1.0,C1,10050383.0,C1,7946.0,AB,10035362.0,B1,10088077.0,C1,10088077.0,C1,JJ048,0.0,20121127.0,NaN
2361,US02,59981,10088178,491036.0,44525.0,69531.0,0.0,605092.0,10088178,201701.0,1245.0,21.0,6.0,2.0,3.0,1.0,D1,10083953.0,C0,10002669.0,AB,10006346.0,B1,10083953.0,C0,10088178.0,D1,LL008,0.0,20121207.0,NaN
1529,US02,59981,10057736,436381.0,68910.0,92908.0,0.0,598199.0,10057736,201701.0,3047.0,42.0,2.0,2.0,1.0,1.0,C1,10003220.0,B1,10055470.0,AF,10003220.0,B1,10057736.0,C1,10057736.0,C1,YA823,0.0,20071101.0,NaN
214,US02,59981,00010523,0.0,0.0,590560.0,1800.0,592360.0,00010523,201701.0,50.0,4.0,1.0,1.0,1.0,1.0,AA,10054645.0,AF,10523.0,AA,10523.0,AA,10523.0,AA,10523.0,AA,JJ003,7900.0,19970701.0,NaN
3121,US02,59981,10015651,377998.0,42888.0,149636.0,0.0,570522.0,10015651,201701.0,1506.0,25.0,2.0,1.0,1.0,1.0,B1,10005754.0,AF,10005754.0,AF,10015651.0,B1,10015651.0,B1,10015651.0,B1,LL059,0.0,20040322.0,NaN
1838,US02,59981,10055470,181376.0,71086.0,307985.0,0.0,560447.0,10055470,201701.0,2980.0,42.0,1.0,1.0,1.0,1.0,AF,10054645.0,AF,10055470.0,AF,10055470.0,AF,10055470.0,AF,10055470.0,AF,YA823,0.0,19891026.0,NaN
510,US02,59981,00025847,21594.0,296331.0,238077.0,0.0,556002.0,00025847,201701.0,9730.0,135.0,1.0,1.0,1.0,1.0,AE,NaN,NaN,25847.0,AE,25847.0,AE,25847.0,AE,25847.0,AE,EE003,4500.0,19920101.0,NaN
3920,US02,59981,10015825,549269.0,0.0,0.0,0.0,549269.0,10015825,201701.0,5952.0,81.0,1.0,3.0,1.0,2.0,E2,40684.0,C1,5195.0,AF,5195.0,AF,40684.0,C1,40684.0,C1,PP041,0.0,20131014.0,NaN
538,US02,59981,00019809,243147.0,161060.0,139222.0,0.0,543429.0,00019809,201701.0,3208.0,44.0,5.0,1.0,1.0,1.0,B1,18153.0,AA,18153.0,AA,19809.0,B1,19809.0,B1,19809.0,B1,AA001,4.0,19930801.0,NaN
217,US02,59981,00013955,0.0,0.0,539946.0,1800.0,541746.0,00013955,201701.0,3331.0,46.0,1.0,1.0,1.0,1.0,AC,16750.0,AA,13955.0,AC,13955.0,AC,13955.0,AC,13955.0,AC,AA028,14800.0,19950101.0,NaN
5470,US02,59981,10101212,539467.0,0.0,0.0,0.0,539467.0,10101212,201701.0,8684.0,119.0,2.0,1.0,1.0,2.0,E2,33352.0,B1,23700.0,AF,33352.0,B1,33352.0,B1,33352.0,B1,QQ039,0.0,20160705.0,NaN
197,US02,59981,00027234,10685.0,144947.0,379181.0,1800.0,536613.0,00027234,201701.0,9149.0,126.0,1.0,1.0,1.0,1.0,AB,23883.0,AD,27234.0,AB,27234.0,AB,27234.0,AB,27234.0,AB,QQ108,0.0,20000427.0,NaN
1427,US02,59981,00019492,6157.0,433437.0,70881.0,0.0,510475.0,00019492,201701.0,6008.0,82.0,1.0,1.0,1.0,1.0,AF,4694.0,AE,19492.0,AF,19492.0,AF,19492.0,AF,19492.0,AF,PP042,0.0,20000405.0,NaN
3209,US02,59981,10004140,273312.0,110160.0,126830.0,0.0,510302.0,10004140,201701.0,4342.0,59.0,2.0,1.0,1.0,1.0,B1,10001287.0,AF,10001287.0,AF,10004140.0,B1,10004140.0,B1,10004140.0,B1,JJ013,0.0,20021114.0,NaN
1133,US02,59981,00040070,256390.0,74432.0,174434.0,0.0,505256.0,00040070,201701.0,1917.0,29.0,2.0,1.0,1.0,1.0,B3,14778.0,AF,14778.0,AF,40070.0,B3,40070.0,B3,40070.0,B3,QQ105,0.0,20010928.0,NaN
546,US02,59981,10003122,384422.0,34855.0,81805.0,0.0,501082.0,10003122,201701.0,3996.0,52.0,6.0,2.0,1.0,1.0,C1,30219.0,B1,6407.0,AF,30219.0,B1,10003122.0,C1,10003122.0,C1,JJ001,0.0,20020805.0,NaN
1802,US02,59981,10056271,90825.0,367152.0,41259.0,0.0,499236.0,10056271,201701.0,2970.0,41.0,4.0,1.0,1.0,1.0,B1,10055028.0,B1,10055468.0,AF,10056271.0,B1,10056271.0,B1,10056271.0,B1,YA812,0.0,19931126.0,NaN
219,US02,59981,00015151,0.0,0.0,494721.0,1800.0,496521.0,00015151,201701.0,7068.0,98.0,1.0,1.0,1.0,1.0,AB,NaN,NaN,15151.0,AB,15151.0,AB,15151.0,AB,15151.0,AB,QQ036,6700.0,20000103.0,NaN
2429,US02,59981,10089331,380324.0,8820.0,105413.0,0.0,494557.0,10089331,201701.0,3356.0,46.0,1.0,2.0,1.0,1.0,C1,13955.0,AC,13955.0,AC,13955.0,AC,10089331.0,C1,10089331.0,C1,AA028,0.0,20130520.0,NaN
3264,US02,59981,10006965,360590.0,50299.0,81108.0,0.0,491997.0,10006965,201701.0,4900.0,66.0,6.0,2.0,1.0,1.0,C1,10002907.0,B3,21334.0,AE,10002907.0,B3,10006965.0,C1,10006965.0,C1,QQ099,0.0,20030211.0,NaN
215,US02,59981,00016779,0.0,123423.0,360621.0,1800.0,485844.0,00016779,201701.0,6438.0,89.0,1.0,1.0,1.0,1.0,AA,NaN,NaN,16779.0,AA,16779.0,AA,16779.0,AA,16779.0,AA,CC006,3000.0,19920601.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8698,US02,59981,10055600,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,US02,59981,00004199,0.0,0.0,0.0,0.0,0.0,00004199,201701.0,3343.0,46.0,1.0,1.0,1.0,13.0,E2,13955.0,AC,13955.0,AC,13955.0,AC,13955.0,AC,13955.0,AC,AA028,0.0,20000721.0,NaN
44,US02,59981,00007532,0.0,0.0,0.0,0.0,0.0,00007532,201701.0,7336.0,102.0,1.0,1.0,1.0,2.0,E2,6712.0,AF,6712.0,AF,6712.0,AF,6712.0,AF,6712.0,AF,FF007,0.0,20141101.0,NaN
50,US02,59981,00003920,0.0,0.0,0.0,0.0,0.0,00003920,201701.0,3220.0,44.0,7.0,1.0,1.0,2.0,E2,11170.0,B1,18153.0,AA,11170.0,B1,11170.0,B1,11170.0,B1,AA001,0.0,20001026.0,NaN
8499,US02,59981,10036042,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,US02,59981,00007566,0.0,0.0,0.0,0.0,0.0,00007566,201701.0,7887.0,111.0,4.0,5.0,1.0,3.0,E2,6795.0,C1,21107.0,AB,23043.0,B1,6795.0,C1,6795.0,C1,FF004,0.0,19970701.0,NaN
41,US02,59981,00007551,0.0,0.0,0.0,0.0,0.0,00007551,201701.0,8643.0,118.0,1.0,1.0,1.0,18.0,E2,23918.0,AF,23918.0,AF,23918.0,AF,23918.0,AF,23918.0,AF,QQ038,0.0,20000306.0,NaN
35,US02,59981,00004204,0.0,0.0,0.0,0.0,0.0,00004204,201701.0,1287.0,21.0,13.0,1.0,1.0,4.0,E2,1697.0,B1,10002669.0,AB,1697.0,B1,1697.0,B1,1697.0,B1,LL008,0.0,19991220.0,NaN
37,US02,59981,00003408,0.0,0.0,0.0,0.0,0.0,00003408,201701.0,2092.0,32.0,1.0,1.0,1.0,5.0,E2,27479.0,AA,27479.0,AA,27479.0,AA,27479.0,AA,27479.0,AA,AA013,8240.0,20040526.0,NaN
48,US02,59981,00003417,0.0,0.0,0.0,0.0,0.0,00003417,201701.0,3763.0,49.0,4.0,2.0,1.0,4.0,E2,10035981.0,C1,2860.0,AF,10015508.0,B1,10035981.0,C1,10035981.0,C1,AA047,0.0,20150225.0,NaN
159,US02,59981,00003035,0.0,-7.0,0.0,0.0,-7.0,00003035,201701.0,3241.0,45.0,1.0,1.0,1.0,12.0,E2,16750.0,AA,16750.0,AA,16750.0,AA,16750.0,AA,16750.0,AA,AA006,0.0,19920301.0,NaN
13,US02,59981,00007404,0.0,-8.0,0.0,0.0,-8.0,00007404,201701.0,8645.0,118.0,1.0,1.0,1.0,20.0,E2,23918.0,AF,23918.0,AF,23918.0,AF,23918.0,AF,23918.0,AF,QQ038,0.0,20000214.0,NaN
151,US02,59981,00002098,0.0,-12.0,0.0,0.0,-12.0,00002098,201701.0,5106.0,68.0,1.0,3.0,1.0,8.0,E2,14674.0,C1,21755.0,AD,21755.0,AD,14674.0,C1,14674.0,C1,QQ051,600.0,19941201.0,NaN
36,US02,59981,00003937,0.0,-36.0,0.0,0.0,-36.0,00003937,201701.0,3345.0,46.0,1.0,1.0,1.0,15.0,E2,13955.0,AC,13955.0,AC,13955.0,AC,13955.0,AC,13955.0,AC,AA028,0.0,19991104.0,NaN
8440,US02,59981,00001047,0.0,-44.0,0.0,0.0,-44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,US02,59981,00007083,0.0,-190.0,138.0,0.0,-52.0,00007083,201701.0,7579.0,106.0,1.0,1.0,4.0,1.0,D1,7262.0,AF,7262.0,AF,7262.0,AF,7262.0,AF,7083.0,D1,JJ042,0.0,19970901.0,NaN
152,US02,59981,00005095,0.0,-80.0,0.0,0.0,-80.0,00005095,201701.0,5635.0,76.0,1.0,1.0,1.0,7.0,E2,6837.0,AF,6837.0,AF,6837.0,AF,6837.0,AF,6837.0,AF,HH031,7.0,19941001.0,NaN
57,US02,59981,00006447,0.0,-312.0,0.0,0.0,-312.0,00006447,201701.0,3471.0,46.0,8.0,1.0,1.0,7.0,E2,13956.0,B3,13955.0,AC,13956.0,B3,13956.0,B3,13956.0,B3,AA028,0.0,19970501.0,NaN
64,US02,59981,00003805,-204.0,-122.0,0.0,0.0,-326.0,00003805,201701.0,3153.0,44.0,1.0,1.0,1.0,13.0,E2,18153.0,AA,18153.0,AA,18153.0,AA,18153.0,AA,18153.0,AA,AA001,0.0,19950801.0,NaN
42,US02,59981,00007533,0.0,-425.0,90.0,0.0,-335.0,00007533,201701.0,7957.0,112.0,2.0,1.0,7.0,1.0,D1,7525.0,B1,6919.0,AE,7525.0,B1,7525.0,B1,7533.0,D1,FF008,0.0,20091001.0,NaN
99,US02,59981,00007225,0.0,-812.0,0.0,0.0,-812.0,00007225,201701.0,7398.0,103.0,1.0,1.0,4.0,3.0,E2,26440.0,D1,24908.0,AD,24908.0,AD,24908.0,AD,26440.0,D1,GG042,0.0,20000807.0,NaN
65,US02,59981,00006697,0.0,-934.0,0.0,0.0,-934.0,00006697,201701.0,7919.0,112.0,1.0,1.0,1.0,4.0,E2,6919.0,AE,6919.0,AE,6919.0,AE,6919.0,AE,6919.0,AE,FF008,0.0,20090713.0,NaN
139,US02,59981,00003310,0.0,-1079.0,0.0,0.0,-1079.0,00003310,201701.0,60.0,4.0,1.0,1.0,1.0,11.0,E2,10523.0,AA,10523.0,AA,10523.0,AA,10523.0,AA,10523.0,AA,JJ003,0.0,19980801.0,NaN
58,US02,59981,00006467,-1080.0,0.0,0.0,0.0,-1080.0,00006467,201701.0,3769.0,49.0,5.0,1.0,1.0,4.0,E2,6229.0,B1,2860.0,AF,6229.0,B1,6229.0,B1,6229.0,B1,AA047,0.0,19940801.0,NaN
89,US02,59981,00007253,-1412.0,0.0,0.0,0.0,-1412.0,00007253,201701.0,7339.0,102.0,1.0,1.0,2.0,3.0,E2,24778.0,D1,6712.0,AF,6712.0,AF,6712.0,AF,24778.0,D1,FF007,6.0,20160620.0,NaN
51,US02,59981,00003916,0.0,-1648.0,0.0,0.0,-1648.0,00003916,201701.0,3147.0,44.0,1.0,1.0,1.0,7.0,E2,18153.0,AA,18153.0,AA,18153.0,AA,18153.0,AA,18153.0,AA,AA001,0.0,20010213.0,NaN
56,US02,59981,00006951,-2541.0,-69.0,0.0,0.0,-2610.0,00006951,201701.0,7399.0,103.0,1.0,1.0,4.0,4.0,E2,26440.0,D1,24908.0,AD,24908.0,AD,24908.0,AD,26440.0,D1,GG042,0.0,19961101.0,NaN
135,US02,59981,00002255,0.0,-4473.0,0.0,0.0,-4473.0,00002255,201701.0,3224.0,44.0,8.0,1.0,1.0,3.0,E2,3252.0,B1,18153.0,AA,3252.0,B1,3252.0,B1,3252.0,B1,AA001,0.0,20001023.0,NaN
8,US02,59981,00005852,-7527.0,0.0,0.0,0.0,-7527.0,00005852,201701.0,3446.0,46.0,6.0,1.0,1.0,7.0,E2,20652.0,B3,13955.0,AC,20652.0,B3,20652.0,B3,20652.0,B3,AA028,0.0,19961101.0,NaN
949,US02,59981,00004632,-81849.0,0.0,50757.0,0.0,-31092.0,00004632,201701.0,6111.0,84.0,1.0,1.0,1.0,1.0,AF,20379.0,AC,4632.0,AF,4632.0,AF,4632.0,AF,4632.0,AF,QQ019,1800.0,19991203.0,NaN

In [153]:
month_table.append(temptable)

  TRANCD JOURNAL_NO   AGNTNUM  FYC  RYC      OR Other
0    NaN        NaN       NaN  NaN  NaN     NaN   NaN
0   US02      59981  00004147    0    0  3087.0     0

In [146]:
month_table=pd.DataFrame(columns=['TRANCD','JOURNAL_NO','AGNTNUM','FYC','RYC','OR','Other'],index=['0'])

In [147]:
month_table

  TRANCD JOURNAL_NO AGNTNUM  FYC  RYC   OR Other
0    NaN        NaN     NaN  NaN  NaN  NaN   NaN

In [114]:
del temptable

In [112]:
pd.DataFrame(columns=['TRANCD','JOURNAL_NO','AGNTNUM','FYC','RYC','OR','Other'],templist)

SyntaxError: positional argument follows keyword argument (<ipython-input-112-f964d839910d>, line 1)

In [ ]:
temptable['TRANCD']=data.TRANCD[0]
temptable['JOURNAL_NO']=data.JOURNAL_NO[0]
temptable['AGNTNUM']=data.AGNTNUM[0]
temptable['FYC']=FYC_Income
temptable['RYC']=RYC_Income
temptable['OR']=OR_Income
temptable['Other']=Other_Income

In [110]:
temptable

Empty DataFrame
Columns: [TRANCD, JOURNAL_NO, AGNTNUM, FYC, RYC, OR, Other]
Index: []

In [102]:
temptable=pd.DataFrame(columns=['TRANCD','JOURNAL_NO','AGNTNUM','FYC','RYC','OR','Other'])

In [103]:
temptable

Empty DataFrame
Columns: [TRANCD, JOURNAL_NO, AGNTNUM, FYC, RYC, OR, Other]
Index: []

In [89]:
temptable['RYC']='213'

In [90]:
temptable

Empty DataFrame
Columns: [TRANCD, JOURNAL_NO, AGNTNUM, FYC, RYC, OR, Other]
Index: []

In [82]:
a=data['INCOME_NO']=='G21'

In [84]:
RYC_table = data[data['INCOME_NO'].isin(RYC_list)]

In [85]:
RYC_table

,TRANCD,JOURNAL_NO,USSEQNO,USSEQ,COMP_NO,AGNTNUM,INCOME_NO,REAMT,WNOTE,MODDATE,POLICYNO,BILLNO,SOUFILE,SOUKEY,DISKSEQ,JOB_NAME,USER_PROFI,FEAT_AMT
1,US02,59981,609048564.0,7784089.0,P,10055460,G21,221.0,林詩綺 年繳 0192 832192,20161115,A8055923848,2 832192,AC08ENQ,712188172,0,L2ACSMTH08,WHDACOP01,0.0
2,US02,59981,609048566.0,7784089.0,P,10055460,G21,134.0,李尚樺 年繳 0192 077123,20170117,A8056253375,2 077123,AC08ENQ,730786881,0,L2ACSMTH08,WHDACOP01,0.0
3,US02,59981,609048572.0,7784089.0,P,10055460,G21,143.0,陳萭甄 年繳 0082 084099,20170103,A805B321488,2 084099,AC08ENQ,730786227,0,L2ACSMTH08,WHDACOP01,0.0
4,US02,59981,609048573.0,7784089.0,P,10055460,G21,307.0,陳萭甄 年繳 0082 084099,20170103,A805B321488,2 084099,AC08ENQ,730786228,0,L2ACSMTH08,WHDACOP01,0.0
5,US02,59981,609048577.0,7784089.0,P,10055460,G21,131.0,徐宏智 年繳 0192 086752,20170104,A8055924911,2 086752,AC08ENQ,730786743,0,L2ACSMTH08,WHDACOP01,0.0
6,US02,59981,609048585.0,7784089.0,P,10055460,G21,367.0,李嘉 年繳 0193 059193,20170104,A8056253997,3 059193,AC08ENQ,730786936,0,L2ACSMTH08,WHDACOP01,0.0
7,US02,59981,609048587.0,7784089.0,P,10055460,G21,304.0,林佑融 年繳 0193 085053,20170104,A8056255009,3 085053,AC08ENQ,730786975,0,L2ACSMTH08,WHDACOP01,0.0
8,US02,59981,609048589.0,7784089.0,P,10055460,G21,281.0,陳又瑄 年繳 0193 088034,20170104,A8056254950,3 088034,AC08ENQ,730786972,0,L2ACSMTH08,WHDACOP01,0.0
9,US02,59981,609048594.0,7784089.0,P,10055460,G21,52.0,劉虹狄 季繳 0735 081022,20170103,A8056255061,5 081022,AC08ENQ,730786981,0,L2ACSMTH08,WHDACOP01,0.0
10,US02,59981,609048599.0,7784089.0,P,10055460,G21,1168.0,王忠義 年繳 0205 115190,20170117,A8055323314,5 115190,AC08ENQ,730786621,0,L2ACSMTH08,WHDACOP01,0.0
11,US02,59981,609048604.0,7784089.0,P,10055460,G21,119.0,徐尉倫 年繳 0196 086750,20170104,A8055924894,6 086750,AC08ENQ,730786727,0,L2ACSMTH08,WHDACOP01,0.0
12,US02,59981,609048555.0,7784089.0,P,10055460,G21,236.0,辜慶恩 年繳 0190 089508,20170104,A8056253904,0 089508,AC08ENQ,730786933,0,L2ACSMTH08,WHDACOP01,0.0
13,US02,59981,609048554.0,7784089.0,P,10055460,G21,291.0,陳柏凡 年繳 0190 088033,20170104,A8056254943,0 088033,AC08ENQ,730786970,0,L2ACSMTH08,WHDACOP01,0.0
14,US02,59981,609048549.0,7784089.0,P,10055460,G21,202.0,殷博文 年繳 0190 075639,20170104,A8055925455,0 075639,AC08ENQ,730786759,0,L2ACSMTH08,WHDACOP01,0.0
15,US02,59981,609048614.0,7784089.0,P,10055460,G21,913.0,鄧子介 年繳 0196 088657,20170104,A8055926236,6 088657,AC08ENQ,730786783,0,L2ACSMTH08,WHDACOP01,0.0
16,US02,59981,609048618.0,7784089.0,P,10055460,G21,141.0,殷曉竹 年繳 0197 075638,20170104,A8055925008,7 075638,AC08ENQ,730786751,0,L2ACSMTH08,WHDACOP01,0.0
17,US02,59981,609048632.0,7784089.0,P,10055460,G21,260.0,辜慶軒 年繳 0197 089507,20170104,A8056253894,7 089507,AC08ENQ,730786930,0,L2ACSMTH08,WHDACOP01,0.0
18,US02,59981,609048643.0,7784089.0,P,10055460,G21,274.0,李冠璋 年繳 0199 059195,20170104,A8056254008,9 059195,AC08ENQ,730786944,0,L2ACSMTH08,WHDACOP01,0.0
19,US02,59981,609048650.0,7784089.0,P,10055460,G21,135.0,李尚蓁 年繳 0209 077122,20170104,A8055188597,9 077122,AC08ENQ,730786558,0,L2ACSMTH08,WHDACOP01,0.0
20,US02,59981,609048657.0,7784089.0,P,10055460,G21,297.0,林佑霖 年繳 0199 085055,20170104,A8056255030,9 085055,AC08ENQ,730786978,0,L2ACSMTH08,WHDACOP01,0.0
21,US02,59981,609048660.0,7784089.0,P,10055460,G21,125.0,徐浩恩 年繳 0199 086751,20170104,A8055924904,9 086751,AC08ENQ,730786735,0,L2ACSMTH08,WHDACOP01,0.0
22,US02,59981,609048550.0,7784089.0,P,10055460,G22,1875.0,殷博文 年繳 0190 075639,20170104,A8055925455,0 075639,AC08ENQ,730786760,0,L2ACSMTH08,WHDACOP01,0.0
23,US02,59981,609048551.0,7784089.0,P,10055460,G22,4.0,殷博文 年繳 0190 075639,20170104,A8055925455,0 075639,AC08ENQ,730786761,0,L2ACSMTH08,WHDACOP01,0.0
24,US02,59981,609048553.0,7784089.0,P,10055460,G22,189.0,吳碧珠 年繳 0190 085052,20170104,A8056254998,0 085052,AC08ENQ,730786974,0,L2ACSMTH08,WHDACOP01,0.0
25,US02,59981,609048556.0,7784089.0,P,10055460,G22,46.0,辜慶恩 年繳 0190 089508,20170104,A8056253904,0 089508,AC08ENQ,730786935,0,L2ACSMTH08,WHDACOP01,0.0
26,US02,59981,609048557.0,7784089.0,P,10055460,G22,43.0,楊式雅 年繳 0210 123813,20170117,A8054534283,0 123813,AC08ENQ,730786419,0,L2ACSMTH08,WHDACOP01,0.0
27,US02,59981,609048637.0,7784089.0,P,10055460,G22,314.0,廖志偉 年繳 0208 833539,20161104,A8055186557,8 833539,AC08ENQ,712188012,0,L2ACSMTH08,WHDACOP01,0.0
28,US02,59981,609048634.0,7784089.0,P,10055460,G22,51.0,辜慶軒 年繳 0197 089507,20170104,A8056253894,7 089507,AC08ENQ,730786932,0,L2ACSMTH08,WHDACOP01,0.0
29,US02,59981,609048633.0,7784089.0,P,10055460,G22,1.0,辜慶軒 年繳 0197 089507,20170104,A8056253894,7 089507,AC08ENQ,730786931,0,L2ACSMTH08,WHDACOP01,0.0
30,US02,59981,609048631.0,7784089.0,P,10055460,G22,488.0,陳亞鍾 年繳 0177 086786,20170104,A8057561961,7 086786,AC08ENQ,730787506,0,L2ACSMTH08,WHDACOP01,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,US02,59981,609048582.0,7784089.0,P,10055460,G23,53.0,徐宏智 年繳 0192 086752,20170104,A8055924911,2 086752,AC08ENQ,730786750,0,L2ACSMTH08,WHDACOP01,0.0
99,US02,59981,609048581.0,7784089.0,P,10055460,G23,164.0,徐宏智 年繳 0192 086752,20170104,A8055924911,2 086752,AC08ENQ,730786749,0,L2ACSMTH08,WHDACOP01,0.0
100,US02,59981,609048578.0,7784089.0,P,10055460,G23,109.0,徐宏智 年繳 0192 086752,20170104,A8055924911,2 086752,AC08ENQ,730786745,0,L2ACSMTH08,WHDACOP01,0.0
101,US02,59981,609048576.0,7784089.0,P,10055460,G23,44.0,陳萭甄 年繳 0082 084099,20170103,A805B321488,2 084099,AC08ENQ,730786231,0,L2ACSMTH08,WHDACOP01,0.0
102,US02,59981,609048575.0,7784089.0,P,10055460,G23,137.0,陳萭甄 年繳 0082 084099,20170103,A805B321488,2 084099,AC08ENQ,730786230,0,L2ACSMTH08,WHDACOP01,0.0
103,US02,59981,609048571.0,7784089.0,P,10055460,G23,53.0,李尚樺 年繳 0192 077123,20170117,A8056253375,2 077123,AC08ENQ,730786888,0,L2ACSMTH08,WHDACOP01,0.0
104,US02,59981,609048570.0,7784089.0,P,10055460,G23,164.0,李尚樺 年繳 0192 077123,20170117,A8056253375,2 077123,AC08ENQ,730786887,0,L2ACSMTH08,WHDACOP01,0.0
105,US02,59981,609048569.0,7784089.0,P,10055460,G23,109.0,李尚樺 年繳 0192 077123,20170117,A8056253375,2 077123,AC08ENQ,730786885,0,L2ACSMTH08,WHDACOP01,0.0
106,US02,59981,609048562.0,7784089.0,P,10055460,G23,329.0,李政宏 年繳 0231 055773,20170103,A8052710461,1 055773,AC08ENQ,730786337,0,L2ACSMTH08,WHDACOP01,0.0
107,US02,59981,609048552.0,7784089.0,P,10055460,G23,415.0,殷博文 年繳 0190 075639,20170104,A8055925455,0 075639,AC08ENQ,730786762,0,L2ACSMTH08,WHDACOP01,0.0
108,US02,59981,609048592.0,7784089.0,P,10055460,G23,329.0,李坤城 年繳 0234 055774,20170103,A8052710492,4 055774,AC08ENQ,730786339,0,L2ACSMTH08,WHDACOP01,0.0
109,US02,59981,609048616.0,7784089.0,P,10055460,G23,126.0,李添猛 年繳 0277 833112,20161117,A8050466241,7 833112,AC08ENQ,712187725,0,L2ACSMTH08,WHDACOP01,0.0
110,US02,59981,609048615.0,7784089.0,P,10055460,G23,83.0,鄧子介 年繳 0196 088657,20170104,A8055926236,6 088657,AC08ENQ,730786784,0,L2ACSMTH08,WHDACOP01,0.0
111,US02,59981,609048613.0,7784089.0,P,10055460,G23,110.0,鄧子介 年繳 0196 088657,20170104,A8055926236,6 088657,AC08ENQ,730786782,0,L2ACSMTH08,WHDACOP01,0.0
112,US02,59981,609048611.0,7784089.0,P,10055460,G23,53.0,鄧子介 年繳 0196 088657,20170104,A8055926236,6 088657,AC08ENQ,730786780,0,L2ACSMTH08,WHDACOP01,0.0
113,US02,59981,609048610.0,7784089.0,P,10055460,G23,332.0,林怡君 年繳 0216 087847,20170104,A8054533189,6 087847,AC08ENQ,730786393,0,L2ACSMTH08,WHDACOP01,0.0
114,US02,59981,609048609.0,7784089.0,P,10055460,G23,109.0,徐尉倫 年繳 0196 086750,20170104,A8055924894,6 086750,AC08ENQ,730786733,0,L2ACSMTH08,WHDACOP01,0.0
115,US02,59981,609048607.0,7784089.0,P,10055460,G23,164.0,徐尉倫 年繳 0196 086750,20170104,A8055924894,6 086750,AC08ENQ,730786730,0,L2ACSMTH08,WHDACOP01,0.0
116,US02,59981,609048605.0,7784089.0,P,10055460,G23,53.0,徐尉倫 年繳 0196 086750,20170104,A8055924894,6 086750,AC08ENQ,730786728,0,L2ACSMTH08,WHDACOP01,0.0
117,US02,59981,609048602.0,7784089.0,P,10055460,G23,205.0,李鈴旭 年繳 0276 077121,20170104,A8050467118,6 077121,AC08ENQ,730786296,0,L2ACSMTH08,WHDACOP01,0.0
118,US02,59981,609048601.0,7784089.0,P,10055460,G23,35.0,王忠義 年繳 0205 115190,20170117,A8055323314,5 115190,AC08ENQ,730786624,0,L2ACSMTH08,WHDACOP01,0.0
119,US02,59981,609048600.0,7784089.0,P,10055460,G23,332.0,王忠義 年繳 0205 115190,20170117,A8055323314,5 115190,AC08ENQ,730786623,0,L2ACSMTH08,WHDACOP01,0.0
120,US02,59981,609048598.0,7784089.0,P,10055460,G23,42.0,劉虹狄 季繳 0735 081022,20170103,A8056255061,5 081022,AC08ENQ,730786986,0,L2ACSMTH08,WHDACOP01,0.0
121,US02,59981,609048597.0,7784089.0,P,10055460,G23,14.0,劉虹狄 季繳 0735 081022,20170103,A8056255061,5 081022,AC08ENQ,730786985,0,L2ACSMTH08,WHDACOP01,0.0
122,US02,59981,609048596.0,7784089.0,P,10055460,G23,28.0,劉虹狄 季繳 0735 081022,20170103,A8056255061,5 081022,AC08ENQ,730786984,0,L2ACSMTH08,WHDACOP01,0.0
123,US02,59981,609048548.0,7784089.0,P,10055460,G23,329.0,李美嬅 年繳 0230 055776,20170103,A8052710564,0 055776,AC08ENQ,730786352,0,L2ACSMTH08,WHDACOP01,0.0
124,US02,59981,609048547.0,7784089.0,P,10055460,G23,307.0,李文安 年繳 0270 041722,20170105,A8050467273,0 041722,AC08ENQ,730786303,0,L2ACSMTH08,WHDACOP01,0.0
125,US02,59981,609048546.0,7784089.0,P,10055460,G23,126.0,李文安 年繳 0270 041722,20170105,A8050467273,0 041722,AC08ENQ,730786301,0,L2ACSMTH08,WHDACOP01,0.0
126,US02,59981,609048624.0,7784089.0,P,10055460,G25,8.0,吳碧珠 年繳 0097 085051,20170104,A805A375345,7 085051,AC08ENQ,730785914,0,L2ACSMTH08,WHDACOP01,0.0
127,US02,59981,609048558.0,7784089.0,P,10055460,G25,63.0,忻元智 年繳 0101 832674,20161103,A8059851099,1 832674,AC08ENQ,712189954,0,L2ACSMTH08,WHDACOP01,0.0

In [233]:
dir_name=r'C:/Users/derrick.wu/Documents/DW/income/CSV'
tablelist=[]
for dirPath, dirNames, fileNames_AB in os.walk(r'C:/Users/derrick.wu/Documents/DW/income/CSV\AB'):
    fileNames_AB=fileNames_AB
    print(dirNames)
for dirPath, dirNames, fileNames_AS in os.walk(r'C:/Users/derrick.wu/Documents/DW/income/CSV\AS'):
    fileNames_AS=fileNames_AS
for k,j in zip(fileNames_AB,fileNames_AS):
    dir_AB_data=r'C:/Users/derrick.wu/Documents/DW/income/CSV/AB/'+k
    dir_AS_data=r'C:/Users/derrick.wu/Documents/DW/income/CSV\AS/'+j
    AB_data = pd.read_csv(dir_AB_data,header=0,encoding = 'ansi',dtype={'業務員代碼':str},low_memory=False)
    AS_data=pd.read_csv(dir_AS_data,header=0,encoding = 'ansi',dtype={'AGNTNUM':str},low_memory=False)
    sector=AS_data.groupby(by='AGNTNUM')
    FYC_list=['G11', 'G12', 'G13', 'G14',
              'G31', 'G34', 'G37', 'G36']
    RYC_list=['G22', 'G23', 'G21', 'G24', 'G25']
    OR_list=['FT','FU','YC', 'YD','FV','BK','OT','BZ','QB', 'FY',"F2","YB"]
    Other_list=['FX1','PK','QB',
                'SH1', 'SH2', 'SH3', 'SH4', 'SH5','SH6', 'SH8', 'SH9', 
                'SI1', 'SI2', 'SI3', 'SI5', 'SI6', 'SI7','SI8', 'SI9']
    FYC_Income_list=[]
    RYC_Income_list=[]
    OR_Income_List=[]
    Other_Income_List=[]
    total_Income_list=[]

    month_table=pd.DataFrame(columns=['TRANCD','JOURNAL_NO','AGNTNUM','FYC','RYC','OR','Other'],index=['0'])
    Agent_list=AS_data['AGNTNUM'].unique()
    for i in Agent_list:
        #temptable=pd.DataFrame()
        data=sector.get_group(i).reset_index(drop=1)
        #篩出來沒東西檢查一下
        FYC_table = data[data['INCOME_NO'].isin(FYC_list)]
        RYC_table = data[data['INCOME_NO'].isin(RYC_list)]
        OR_table = data[data['INCOME_NO'].isin(OR_list)]
        Other_table = data[data['INCOME_NO'].isin(Other_list)]
        FYC_Income=sum(FYC_table['REAMT'])
        FYC_Income_list=FYC_Income_list+[FYC_Income]

        RYC_Income=sum(RYC_table['REAMT'])
        RYC_Income_list=RYC_Income_list+[RYC_Income]

        OR_Income=sum(OR_table['REAMT'])
        OR_Income_List=OR_Income_List+[OR_Income]

        Other_Income=sum(Other_table['REAMT'])
        Other_Income_List=Other_Income_List+[Other_Income]

        total=FYC_Income+RYC_Income+OR_Income+Other_Income
        total_Income_list=total_Income_list+[total]

        dict_={
        'TRANCD':data.TRANCD[0],
        'JOURNAL_NO':data.JOURNAL_NO[0],
        'AGNTNUM':Agent_list,
        'FYC':FYC_Income_list,
        'RYC':RYC_Income_list,
        'OR':OR_Income_List,
        'Other':Other_Income_List, 
        'Total':total_Income_list
        }
    month_table=pd.DataFrame(dict_)
    monthtable_merge=month_table.merge(AB_data,how='left',left_on=['AGNTNUM'],right_on=['業務員代碼'])
    monthtable_merge.sort_values(by='Total',ascending=0)
    tablelist=tablelist+[monthtable_merge]
    print(j)
    #del temptable

[]

D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

AS041301.csv
AS041302.csv

D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

AS041303.csv
AS041304.csv
AS041305.csv
AS041306.csv
AS041307.csv
AS041308.csv
AS041309.csv
AS041310.csv
AS041311.csv
AS041312.csv
AS041401.csv
AS041402.csv
AS041403.csv
AS041404.csv
AS041405.csv
AS041406.csv
AS041407.csv
AS041408.csv
AS041409.csv
AS041410.csv
AS041411.csv
AS041412.csv
AS041501.csv
AS041502.csv
AS041503.csv
AS041504.csv
AS041505.csv
AS041506.csv
AS041507.csv
AS041508.csv
AS041509.csv
AS041510.csv
AS041511.csv
AS041512.csv
AS041601.csv
AS041602.csv
AS041603.csv
AS041604.csv
AS041605.csv
AS041606.csv
AS041607.csv
AS041608.csv
AS041609.csv
AS041610.csv
AS041611.csv
AS041612.csv
AS041701.csv
AS041702.csv
AS041703.csv
AS041704.csv
AS041705.csv
AS041706.csv
AS041707.csv
AS041708.csv
AS041709.csv
AS041710.csv
AS041711.csv
AS041712.csv

In [243]:
income_table=pd.DataFrame()
for s in tablelist:
    income_table=income_table.append(s,sort=False)

In [244]:
income_table = income_table.dropna(axis=0, how='any', thresh=None, subset=['工作月份'])

In [247]:
income_table=income_table.sort_values(by=['工作月份','AGNTNUM'])

In [248]:
income_table.to_csv('income_data.csv',encoding='utf-8')